location = SUBFOLDERweharbor.webmanifest {
  alias /usr/share/selkies/web/weharbor.webmanifest;
  default_type application/manifest+json;
  add_header Cache-Control "no-cache";
}
location = SUBFOLDERweharbor-sw.js {
  alias /usr/share/selkies/web/weharbor-sw.js;
  default_type application/javascript;
  add_header Cache-Control "no-cache";
}
location = SUBFOLDERweharbor-pwa.js {
  alias /usr/share/selkies/web/weharbor-pwa.js;
  default_type application/javascript;
  add_header Cache-Control "no-cache";
}
